### ISSUE TITLE
Be able to get info for tv show via Imdb id.

### ISSUE THREAD

**Issue by Ephil012** [worr/node-imdb-api#26]

**Comment by worr** [comment]
Hey, can you give me a bit more context here? This should already be possible.

**Comment by kilianc** [comment]
@worr I am curretly getting `episode not valid` if I do `imdb.getById('tt0869673)` which is one of the ids in your examples

**Comment by mwilliammyers** [comment]
Here is an example of the error I get when I call `imdb.getById('tt5207730')` for [this](http://www.imdb.com/title/tt5207730/) Walking Dead episode:
```
ImdbError {
  message: 'type: episode not valid',
  movie: { id: 'tt5207730', name: undefined },
  name: 'imdb api error' }
```

If I am reading [line 188](https://github.com/worr/node-imdb-api/blob/057d3d76d3feb5560502f8b919c1e076873f66fb/src/imdb.ts#L188) correctly this API is assuming all `getReq` are of `type` movie...?

It looks like the [OMDb API](https://www.omdbapi.com) allows for a `type` param in the request. Maybe adding `getEpisodeById()` and a `getMovieById()` and a `getSeriesById()` (the types the API allows for) would be a good idea? Or try each in some order until we get a hit and return that?

**Comment by worr** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

I don't plan on adding these methods to the API, because I don't think that the user should necessarily need to know the type.

I'll definitely fix this though, so the get functions support this.

El 25 de noviembre de 2016 7:41:06 PM PST, mwilliammyers <notifications@github.com> escribió:
>Here is an example of the error I get when I call
>`imdb.getById('tt5207730')` for
>[this](http://www.imdb.com/title/tt5207730/) Walking Dead episode:
>```
>ImdbError {
>  message: 'type: episode not valid',
>  movie: { id: 'tt5207730', name: undefined },
>  name: 'imdb api error' }
>```
>
>If I am reading [line
>188](https://github.com/worr/node-imdb-api/blob/057d3d76d3feb5560502f8b919c1e076873f66fb/src/imdb.ts#L188)
>correctly this API is assuming all `getReq` are of `type` movie...?
>
>It looks like the [OMDb API](https://www.omdbapi.com) allows for a
>`type` param in the request. Maybe adding `getEpisodeById()` and a
>`getMovieById()` and a `getSeriesById()` (the types the API allows for)
>would be a good idea? Or try each in some order until we get a hit and
>return that?

- --
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-----BEGIN PGP SIGNATURE-----

iQI9BAEBCgAnIBxXaWxsaWFtIE9yciA8d2lsbEB3b3JyYmFzZS5jb20+BQJYPjgY
AAoJEOWIWopNkblk6BIP/j9TN0NkYN0XT0bd+ygTuNpu+BuKrQY0O0ZBKHmHFZIG
0+C4F3n0/CQLeh9CtYEGveYrb2srEwfks1YeVkSY3LZxNw5B833pX3dgJ8prSsfQ
+jOudZasjrscPku9DmYYVyzJj+0GNrpKbE+PnDqz2Psrai4KVr4R27fEc7dWjspx
C6WjkulvOeChixssUcGbfGCo4XE5ENbalzKmPmdz7OsU4cBPfwLEsPm/UCnSMkir
hB2tm7PODeFkDR402gAGDfxDCokDsOjJyhuIWGbotdjeb+aczEvktUKabW65DzF1
RpMGthx6e5gmaEUemwRbLPDEMywKwOmPxzLZiZguvEPrWWrqXRIGb/9wnyEB6bSy
9EgAvTRYW3dWaT5vrqwcNXW02QAl2IJUQGcOgZCwonDD6WYUm0nvBrAUh0pnE7Lr
TDC5veBqHt7FeBwDEdWgamJT2mtBoB+E40N7ewDlmFPX6BzlaHkFU1bLWk9RUCnE
NZTdS5g8fWAZcTUxODJzEAJ+/6bfzWN5/WNITD6FMB9b6TMyLCewHJNqrIBynQhR
CPr08zrR+jFmnm8M8l5ofhIuVBcpoaThc5qxBl0d6+zc0uwcuuXF9R3aJ1N6w+mx
dA19m9N0f9WWbbWhknxyqfi2HTBSZZsHSgEer1IAy/PwEdiLW9ZPu8o0uMpim10h
=iEzh
-----END PGP SIGNATURE-----
