### ISSUE TITLE
Response data isn't accurate with what's on the website.

### ISSUE THREAD

**Issue by awarmfastbear** [worr/node-imdb-api#70]
The IMDB ID: tt1519397

Shows a rating of 9.4 with 5 votes at the time of writing this from the API, if you go to the IMDB site it's 6.7 with 13 votes.

The ID of tt1539700

Has a rating of 8.4 with 36 votes but the website shows a rating of 8.5 with 60 votes. 

Also, the ID of 1090023 fails to fetch for me but I can see it here: https://www.imdb.com/title/tt1090023/ super weird.

```
tmp_id = 'tt1090023'
imdb.get({ id: tmp_id }, { apiKey: _api_key }).then(console.log).catch(error => {
    console.log('Error', error);
});
```
```
Error TypeError: invalid episode
    at new Episode (./node_modules/imdb-api/lib/imdb.js:96:23)
```

Do you know why the API response data is not the same as the website?

**Comment by worr** [comment]
The API I use is [omdb](https://omdbapi.com). All three of these are data quality issues - I don't know how often they fetch data from imdb, or how good the data dumps from imdb that they use are.

The last one looks more confusing, but that's because the API returns `"N/A"` as the result for both the season and episode, which can't be converted into an integer.

I recommend filing issues about data quality at their github: https://github.com/omdbapi/OMDb-API
